name: Run Bot 24/7

on:
  push:
  schedule:
    - cron: '0 */3 * * *' # Запуск каждые 3 часа
  workflow_dispatch: # Добавил возможность запускать вручную для проверки

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram Bot
        timeout-minutes: 150 
        env:
          # ВАЖНО: Замените имена справа (secrets.XXX) на те, что у вас в настройках GitHub
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }} 
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Сохранение изменений в GitHub
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add db_shop.json db_tickets.json
          
          git commit -m "Авто-сохранение базы данных [skip ci]" || echo "Нет изменений для коммита"
          git push
